import React from 'react';
import {
  LightBulbIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  BeakerIcon,
} from '@heroicons/react/24/outline';

import ThreeRatioTable1 from './ThreeRatioMethodTable1';
import ThreeRatioTable2 from './ThreeRatioMethodTable2';
import ThreeRatioDiagnosisList from './ThreeRatioDiagnosisList';
import ThreeRatioDiagnosisCodeTable from './ThreeRatioDiagnosisCodeTable';

const ThreeRatioMethodContent = () => {
  return (
    <>
      <h3 className="text-2xl font-bold bg-gradient-to-r from-purple-500 to-indigo-500 text-transparent bg-clip-text">
        The Three Ratio Technique (TRT)
      </h3>

      <div className="mt-6 space-y-8 max-h-[600px] overflow-y-auto pr-4">
        <div className="p-6 bg-white/50 dark:bg-slate-800/50 rounded-xl shadow-md border border-slate-200 dark:border-slate-700">
          <div className="flex items-center gap-3">
            <LightBulbIcon className="w-6 h-6 text-purple-500" />
            <h4 className="text-lg font-bold text-slate-800 dark:text-slate-200">
              Underlying Concept
            </h4>
          </div>
          <ul className="mt-3 space-y-3 list-disc pl-5 text-slate-600 dark:text-slate-300 text-justify">
            <li>
              In 2018, a new diagnostic technique named as "The Three Ratio
              Technique (TRT)" was proposed.
            </li>
            <li>
              This technique is built on the consideration of five combustible
              gases generated by internal faults: Hydrogen (H₂), Methane (CH₄),
              Ethane (C₂H₆), Ethylene (C₂H₄), and Acetylene (C₂H₂).
            </li>
            <li>
              It detects five abnormal conditions: normal ageing, thermal
              decomposition, partial discharge, arcing, and a mix of thermal and
              electrical faults.
            </li>
            <li>
              The TRT diagnosis technique suggests three gas-ratio combinations
              that are able to classify the fault type and its severity clearly.
            </li>
          </ul>
        </div>

        {/* ============================================================= */}
        {/* NEW: Redesigned Ratio Definitions Section                     */}
        {/* ============================================================= */}
        <div className="space-y-4">
          <div className="flex items-center gap-3">
            <BeakerIcon className="w-6 h-6 text-purple-500" />
            <h4 className="text-lg font-bold text-slate-800 dark:text-slate-200">
              Ratio Definitions & Interpretation
            </h4>
          </div>
          {/* Ratio 1 Card */}
          <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-lg border border-slate-200 dark:border-slate-700 md:flex md:items-center md:gap-6">
            <p className="font-mono text-lg font-bold text-[#1f75fe] dark:text-sky-400 md:w-3/5 text-center md:text-right">
              R₁ = (C₂H₆ + C₂H₄) / (H₂ + C₂H₂)
            </p>
            <p className="mt-2 md:mt-0 text-sm text-slate-600 dark:text-slate-300 text-justify md:w-3/5 md:border-l md:border-slate-300 dark:md:border-slate-600 md:pl-6">
              The ratio R₁ is able to distinguish between thermal decomposition,
              arcing, and partial discharge faults.
            </p>
          </div>
          {/* Ratio 2 Card */}
          <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-lg border border-slate-200 dark:border-slate-700 md:flex md:items-center md:gap-6">
            <p className="font-mono text-lg font-bold text-[#1f75fe] dark:text-sky-400 md:w-3/5 text-center md:text-left">
              R₂ = (C₂H₂ + CH₄) / C₂H₄
            </p>
            <p className="mt-2 md:mt-0 text-sm text-slate-600 dark:text-slate-300 text-justify md:w-3/5 md:border-l md:border-slate-300 dark:md:border-slate-600 md:pl-6">
              For electrical and thermal faults, D₁ and D₂ faults of low and
              high arcing discharge and also T₁, T₂, and T₃ faults can be
              discriminated by ratio R₂.
            </p>
          </div>
          {/* Ratio 3 Card */}
          <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-lg border border-slate-200 dark:border-slate-700 md:flex md:items-center md:gap-6">
            <p className="font-mono text-lg font-bold text-[#1f75fe] dark:text-sky-400 md:w-3/5 text-center md:text-left">
              R₃ = C₂H₂ / C₂H₄
            </p>
            <p className="mt-2 md:mt-0 text-sm text-slate-600 dark:text-slate-300 text-justify md:w-3/5 md:border-l md:border-slate-300 dark:md:border-slate-600 md:pl-6">
              The gas ratio R3 is used in existing diagnosis techniques of
              Doernenburg, Rogers and IEC.The gas ratio R₃ is used in existing
              techniques of Doornenburg, Rogers and IEC. It is usually able to
              distinguish between thermal and electrical faults but unable to
              discern between PD, D₁ and D₂ faults. It confirms the fault type
              from R₁.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-6">
          <ThreeRatioTable1 />
        </div>

        <div className="grid grid-cols-1 gap-6">
          <ThreeRatioTable2 />
        </div>
        <div className="grid grid-cols-1 gap-6">
          <ThreeRatioDiagnosisList />
        </div>

        <div className="grid grid-cols-1 gap-6">
          <ThreeRatioDiagnosisCodeTable />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-green-50 dark:bg-green-900/40 p-4 rounded-lg border border-green-200 dark:border-green-800">
            <div className="flex items-center gap-2">
              <ShieldCheckIcon className="w-6 h-6 text-green-500" />
              <h5 className="font-semibold text-green-700 dark:text-green-300">
                Advantages
              </h5>
            </div>
            <ul className="mt-2 pl-4 list-disc list-outside text-sm text-slate-600 dark:text-slate-400 space-y-1">
              <li>Identify faults PD1, PD2, D1, D2, T1, T2, T3, T0, DT.</li>
              <li>Has an accuracy of 99.86%, compared to other methods.</li>
            </ul>
          </div>
          <div className="bg-orange-50 dark:bg-orange-900/40 p-4 rounded-lg border border-orange-200 dark:border-orange-800">
            <div className="flex items-center gap-2">
              <ShieldExclamationIcon className="w-6 h-6 text-orange-500" />
              <h5 className="font-semibold text-orange-700 dark:text-orange-300">
                Disadvantages
              </h5>
            </div>
            <ul className="mt-2 pl-4 list-disc list-outside text-sm text-slate-600 dark:text-slate-400 space-y-1">
              <li>
                Provides insufficient information for multiple faults or cases
                that fall outside specified codes.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </>
  );
};

export default ThreeRatioMethodContent;
